require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe McategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Mcategory. As you add validations to Mcategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # McategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mcategories as @mcategories" do
      mcategory = Mcategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mcategories).should eq([mcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested mcategory as @mcategory" do
      mcategory = Mcategory.create! valid_attributes
      get :show, {:id => mcategory.to_param}, valid_session
      assigns(:mcategory).should eq(mcategory)
    end
  end

  describe "GET new" do
    it "assigns a new mcategory as @mcategory" do
      get :new, {}, valid_session
      assigns(:mcategory).should be_a_new(Mcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested mcategory as @mcategory" do
      mcategory = Mcategory.create! valid_attributes
      get :edit, {:id => mcategory.to_param}, valid_session
      assigns(:mcategory).should eq(mcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mcategory" do
        expect {
          post :create, {:mcategory => valid_attributes}, valid_session
        }.to change(Mcategory, :count).by(1)
      end

      it "assigns a newly created mcategory as @mcategory" do
        post :create, {:mcategory => valid_attributes}, valid_session
        assigns(:mcategory).should be_a(Mcategory)
        assigns(:mcategory).should be_persisted
      end

      it "redirects to the created mcategory" do
        post :create, {:mcategory => valid_attributes}, valid_session
        response.should redirect_to(Mcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mcategory as @mcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mcategory.any_instance.stub(:save).and_return(false)
        post :create, {:mcategory => {}}, valid_session
        assigns(:mcategory).should be_a_new(Mcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mcategory.any_instance.stub(:save).and_return(false)
        post :create, {:mcategory => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mcategory" do
        mcategory = Mcategory.create! valid_attributes
        # Assuming there are no other mcategories in the database, this
        # specifies that the Mcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mcategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mcategory.to_param, :mcategory => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mcategory as @mcategory" do
        mcategory = Mcategory.create! valid_attributes
        put :update, {:id => mcategory.to_param, :mcategory => valid_attributes}, valid_session
        assigns(:mcategory).should eq(mcategory)
      end

      it "redirects to the mcategory" do
        mcategory = Mcategory.create! valid_attributes
        put :update, {:id => mcategory.to_param, :mcategory => valid_attributes}, valid_session
        response.should redirect_to(mcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the mcategory as @mcategory" do
        mcategory = Mcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => mcategory.to_param, :mcategory => {}}, valid_session
        assigns(:mcategory).should eq(mcategory)
      end

      it "re-renders the 'edit' template" do
        mcategory = Mcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => mcategory.to_param, :mcategory => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mcategory" do
      mcategory = Mcategory.create! valid_attributes
      expect {
        delete :destroy, {:id => mcategory.to_param}, valid_session
      }.to change(Mcategory, :count).by(-1)
    end

    it "redirects to the mcategories list" do
      mcategory = Mcategory.create! valid_attributes
      delete :destroy, {:id => mcategory.to_param}, valid_session
      response.should redirect_to(mcategories_url)
    end
  end

end
