require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NutrDefsController do

  # This should return the minimal set of attributes required to create a valid
  # NutrDef. As you add validations to NutrDef, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NutrDefsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nutr_defs as @nutr_defs" do
      nutr_def = NutrDef.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nutr_defs).should eq([nutr_def])
    end
  end

  describe "GET show" do
    it "assigns the requested nutr_def as @nutr_def" do
      nutr_def = NutrDef.create! valid_attributes
      get :show, {:id => nutr_def.to_param}, valid_session
      assigns(:nutr_def).should eq(nutr_def)
    end
  end

  describe "GET new" do
    it "assigns a new nutr_def as @nutr_def" do
      get :new, {}, valid_session
      assigns(:nutr_def).should be_a_new(NutrDef)
    end
  end

  describe "GET edit" do
    it "assigns the requested nutr_def as @nutr_def" do
      nutr_def = NutrDef.create! valid_attributes
      get :edit, {:id => nutr_def.to_param}, valid_session
      assigns(:nutr_def).should eq(nutr_def)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NutrDef" do
        expect {
          post :create, {:nutr_def => valid_attributes}, valid_session
        }.to change(NutrDef, :count).by(1)
      end

      it "assigns a newly created nutr_def as @nutr_def" do
        post :create, {:nutr_def => valid_attributes}, valid_session
        assigns(:nutr_def).should be_a(NutrDef)
        assigns(:nutr_def).should be_persisted
      end

      it "redirects to the created nutr_def" do
        post :create, {:nutr_def => valid_attributes}, valid_session
        response.should redirect_to(NutrDef.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nutr_def as @nutr_def" do
        # Trigger the behavior that occurs when invalid params are submitted
        NutrDef.any_instance.stub(:save).and_return(false)
        post :create, {:nutr_def => {}}, valid_session
        assigns(:nutr_def).should be_a_new(NutrDef)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NutrDef.any_instance.stub(:save).and_return(false)
        post :create, {:nutr_def => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nutr_def" do
        nutr_def = NutrDef.create! valid_attributes
        # Assuming there are no other nutr_defs in the database, this
        # specifies that the NutrDef created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NutrDef.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nutr_def.to_param, :nutr_def => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nutr_def as @nutr_def" do
        nutr_def = NutrDef.create! valid_attributes
        put :update, {:id => nutr_def.to_param, :nutr_def => valid_attributes}, valid_session
        assigns(:nutr_def).should eq(nutr_def)
      end

      it "redirects to the nutr_def" do
        nutr_def = NutrDef.create! valid_attributes
        put :update, {:id => nutr_def.to_param, :nutr_def => valid_attributes}, valid_session
        response.should redirect_to(nutr_def)
      end
    end

    describe "with invalid params" do
      it "assigns the nutr_def as @nutr_def" do
        nutr_def = NutrDef.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NutrDef.any_instance.stub(:save).and_return(false)
        put :update, {:id => nutr_def.to_param, :nutr_def => {}}, valid_session
        assigns(:nutr_def).should eq(nutr_def)
      end

      it "re-renders the 'edit' template" do
        nutr_def = NutrDef.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NutrDef.any_instance.stub(:save).and_return(false)
        put :update, {:id => nutr_def.to_param, :nutr_def => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nutr_def" do
      nutr_def = NutrDef.create! valid_attributes
      expect {
        delete :destroy, {:id => nutr_def.to_param}, valid_session
      }.to change(NutrDef, :count).by(-1)
    end

    it "redirects to the nutr_defs list" do
      nutr_def = NutrDef.create! valid_attributes
      delete :destroy, {:id => nutr_def.to_param}, valid_session
      response.should redirect_to(nutr_defs_url)
    end
  end

end
