require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServSizesController do

  # This should return the minimal set of attributes required to create a valid
  # ServSize. As you add validations to ServSize, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServSizesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all serv_sizes as @serv_sizes" do
      serv_size = ServSize.create! valid_attributes
      get :index, {}, valid_session
      assigns(:serv_sizes).should eq([serv_size])
    end
  end

  describe "GET show" do
    it "assigns the requested serv_size as @serv_size" do
      serv_size = ServSize.create! valid_attributes
      get :show, {:id => serv_size.to_param}, valid_session
      assigns(:serv_size).should eq(serv_size)
    end
  end

  describe "GET new" do
    it "assigns a new serv_size as @serv_size" do
      get :new, {}, valid_session
      assigns(:serv_size).should be_a_new(ServSize)
    end
  end

  describe "GET edit" do
    it "assigns the requested serv_size as @serv_size" do
      serv_size = ServSize.create! valid_attributes
      get :edit, {:id => serv_size.to_param}, valid_session
      assigns(:serv_size).should eq(serv_size)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServSize" do
        expect {
          post :create, {:serv_size => valid_attributes}, valid_session
        }.to change(ServSize, :count).by(1)
      end

      it "assigns a newly created serv_size as @serv_size" do
        post :create, {:serv_size => valid_attributes}, valid_session
        assigns(:serv_size).should be_a(ServSize)
        assigns(:serv_size).should be_persisted
      end

      it "redirects to the created serv_size" do
        post :create, {:serv_size => valid_attributes}, valid_session
        response.should redirect_to(ServSize.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serv_size as @serv_size" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServSize.any_instance.stub(:save).and_return(false)
        post :create, {:serv_size => {}}, valid_session
        assigns(:serv_size).should be_a_new(ServSize)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServSize.any_instance.stub(:save).and_return(false)
        post :create, {:serv_size => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serv_size" do
        serv_size = ServSize.create! valid_attributes
        # Assuming there are no other serv_sizes in the database, this
        # specifies that the ServSize created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServSize.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => serv_size.to_param, :serv_size => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested serv_size as @serv_size" do
        serv_size = ServSize.create! valid_attributes
        put :update, {:id => serv_size.to_param, :serv_size => valid_attributes}, valid_session
        assigns(:serv_size).should eq(serv_size)
      end

      it "redirects to the serv_size" do
        serv_size = ServSize.create! valid_attributes
        put :update, {:id => serv_size.to_param, :serv_size => valid_attributes}, valid_session
        response.should redirect_to(serv_size)
      end
    end

    describe "with invalid params" do
      it "assigns the serv_size as @serv_size" do
        serv_size = ServSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServSize.any_instance.stub(:save).and_return(false)
        put :update, {:id => serv_size.to_param, :serv_size => {}}, valid_session
        assigns(:serv_size).should eq(serv_size)
      end

      it "re-renders the 'edit' template" do
        serv_size = ServSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServSize.any_instance.stub(:save).and_return(false)
        put :update, {:id => serv_size.to_param, :serv_size => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serv_size" do
      serv_size = ServSize.create! valid_attributes
      expect {
        delete :destroy, {:id => serv_size.to_param}, valid_session
      }.to change(ServSize, :count).by(-1)
    end

    it "redirects to the serv_sizes list" do
      serv_size = ServSize.create! valid_attributes
      delete :destroy, {:id => serv_size.to_param}, valid_session
      response.should redirect_to(serv_sizes_url)
    end
  end

end
